### ISSUE TITLE
why not sign function for gradient under linf norm

### ISSUE THREAD

**Issue by Equationliu** [jeromerony/adversarial-library#4]
Using l2 normalization under linf attack is unreasonable, making the step size much smaller than alpha.

```
# normalize gradient
grad_l2_norms = δ_grad.flatten(1).norm(p=2, dim=1).clamp_min(1e-12)
δ_grad.div_(batch_view(grad_l2_norms))

# gradient ascent step
δ.data.add_(δ_grad, alpha=α)
```

**Comment by jeromerony** [comment]
Hi,
I assume this is from the FMN attack [code](https://github.com/jeromerony/adversarial-library/blob/main/adv_lib/attacks/fast_minimum_norm.py), which you have not linked.
This code is based on the [original implementation](https://github.com/maurapintor/Fast-Minimum-Norm-FMN-Attack/blob/main/src/attacks/fmn.py) and the algorithm provided in the [original paper](https://arxiv.org/abs/2102.12827).

If you have suggestions to improve this attack, you should probably contact the main author @maurapintor

**Comment by Equationliu** [comment]
Thanks for your kind reply!
