### ISSUE TITLE
Requirements python3.8

### ISSUE THREAD

**Issue by Daulbaev** [jeromerony/adversarial-library#5]
I receive the following error during the installation:
ERROR: Package 'adv-lib' requires a different Python: 3.6.8 not in '>=3.8'

Are the additional features of python3.8 really used? I managed to install the library using "python3 setup.py install" without pip.

**Comment by jeromerony** [comment]
So I am not sure the requirement is hard. But I am mainly developing in python 3.8, so I can't guarantee that it will work as intended for previous versions, hence the requirement.
