### ISSUE TITLE
A little Bug?

### ISSUE THREAD

**Issue by yrj1409** [jeromerony/adversarial-library#7]
in adv_lib/attacks/auto_pgd.py

line 380
x_adv = inputs + t * batch_view(eps / t.flatten(1).norm(p=2, dim=1) + 1e-12)
seems to be

x_adv = inputs + t * batch_view(eps / (t.flatten(1).norm(p=2, dim=1) + 1e-12))

**Comment by jeromerony** [comment]
Hi!
Indeed, this is an error. Thankfully, it does not result in any division by 0 since `t` is a random vector, so its norm is never 0.
Thanks for spotting this!
