### ISSUE TITLE
Error when using float absolute step size with PGD attack

### ISSUE THREAD

**Issue by lucascionis** [jeromerony/adversarial-library#9]
[PGD implementation](https://github.com/jeromerony/adversarial-library/blob/main/adv_lib/attacks/projected_gradient_descent.py) gives a problem with batch view when setting absolute step size to a float value:

>  δ_grad = grad(loss.sum(), δ, only_inputs=True)[0].sign_().mul_(batch_view(step_size)), **line 104**
> batch_view = lambda tensor: tensor.view(batch_size, *[1] * (inputs.ndim - 1))
> AttributeError: 'float' object has no attribute 'view'

shouldn't it be set to a tensor? Like the relative step size when multiplied by epsilon.

**Comment by jeromerony** [comment]
Hi!
Indeed, you are right. I think I simply never used this option after I made it possible to provide per-sample `ε`.
